<?xml version="1.0"?>

<robot name="sea_snake" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:property name="length" value="0.05" />
  <xacro:property name="radius" value="0.025" />
  <xacro:property name="mass" value="0.159" />
  <xacro:property name="ixx" value="0.000057969" />
  <xacro:property name="iyy" value="0.000057969" />
  <xacro:property name="izz" value="0.000049687" />
  <xacro:property name="ixy" value="0.0" />
  <xacro:property name="iyz" value="0.0" />
  <xacro:property name="ixz" value="0.0" />
  <xacro:property name="ixz" value="0.0" />
  <xacro:property name="friction" value="0.2" />
  <xacro:property name="damping" value="0.001" />
  <xacro:property name="spring_mass" value="0.001" />
  <xacro:property name="spring_inertia" value="0.0" />


  <xacro:macro name="snakelink" params="num">
    <link name="module_${num}">

      <collision>
      	<geometry>
          <cylinder length="${length}" radius="${radius}" />
      	</geometry>
      	<origin xyz="0 0 -${length/2}" rpy="0 0 0" />
      </collision>

      <visual>
	<geometry>
	  <cylinder length="${length}" radius="${radius}" />
	</geometry>
	<origin xyz="0 0 -${length/2}" rpy="0 0 0" />
      </visual>

      <inertial>
	<origin xyz="0 0 -${length/2}" rpy="0 0 0" />
	<mass value="0.159" />
	<inertia
            ixx="${ixx}" ixy="${ixy}" ixz="${ixz}"
            iyy="${iyy}" iyz="${iyz}"
	    izz="${izz}" />
      </inertial>
    </link>    
  </xacro:macro>

  <xacro:macro name="sea_joint" params="parent child axis">
    <joint name="joint_${parent}_m" type="revolute">
      <limit effort="1000.0" lower="-${pi/2}" upper="${pi/2}" velocity="10" />
      <dynamics damping="${damping}" friction="${friction}" />
      <parent link="module_${parent}" />
      <child link="spring_${parent}" />
      <origin xyz="0 0 -${length}" />
      <axis xyz="${axis}"/>
    </joint>
    <link name="spring_${parent}">
      <visual>
	<geometry>
	  <cylinder length="${2*radius}" radius=".001" />
	</geometry>
	<origin xyz="0 0 0" rpy="${pi/2} 0 0" />
      </visual>
      <inertial>
	<mass value="${spring_mass}" />
	<inertia
            ixx="${spring_inertia}" ixy="0.0" ixz="0.0"
            iyy="${spring_inertia}" iyz="0.0"
    	    izz="${spring_inertia}" />
      </inertial>
    </link>
    <joint name="joint_${parent}_${child}" type="revolute">
      <limit effort="1000.0" lower="-${pi/2}" upper="${pi/2}" velocity="10" />
      <!-- <dynamics damping="${damping}" friction="${friction}" /> -->
      <parent link="spring_${parent}" />
      <child link="module_${child}" />
      <origin xyz="0 0 0" rpy="0 0 0" />
      <axis xyz="${axis}"/>
    </joint>
  </xacro:macro>

  <xacro:macro name="usnake_joint" params="parent child axis">
    <joint name="joint_${parent}_${child}" type="revolute">
      <limit effort="1000.0" lower="-${pi/2}" upper="${pi/2}" velocity="10" />
      <dynamics damping="${damping}" friction="${friction}" />
      <parent link="module_${parent}" />
      <child link="module_${child}" />
      <origin xyz="0 0 -${length}" />
      <axis xyz="${axis}" />
    </joint>
  </xacro:macro>




  <!-- Used for fixing robot to Gazebo 'base_link' -->       
  <link name="world" />
  <joint name="fixed" type="fixed">
    <parent link="world" />
    <child link="module_0" />
  </joint>

  <!-- uncomment for sea_snake joints -->

  <!-- <xacro:snakelink num="0" /> -->
  <!-- <xacro:sea_joint parent="0" child="1" axis="0 1 0" /> -->
  <!-- <xacro:snakelink num="1" /> -->
  <!-- <xacro:sea_joint parent="1" child="2" axis="1 0 0" /> -->
  <!-- <xacro:snakelink num="2" /> -->
  <!-- <xacro:sea_joint parent="2" child="3" axis="0 1 0" /> -->
  <!-- <xacro:snakelink num="3" /> -->
  <!-- <xacro:sea_joint parent="3" child="4" axis="1 0 0" /> -->
  <!-- <xacro:snakelink num="4" /> -->
  <!-- <xacro:sea_joint parent="4" child="5" axis="0 1 0" /> -->
  <!-- <xacro:snakelink num="5" /> -->
  <!-- <xacro:sea_joint parent="5" child="6" axis="1 0 0" /> -->
  <!-- <xacro:snakelink num="6" /> -->
  <!-- <xacro:sea_joint parent="6" child="7" axis="0 1 0" /> -->
  <!-- <xacro:snakelink num="7" /> -->
  <!-- <xacro:sea_joint parent="7" child="8" axis="1 0 0" /> -->
  <!-- <xacro:snakelink num="8" /> -->
  <!-- <xacro:sea_joint parent="8" child="9" axis="0 1 0" /> -->
  <!-- <xacro:snakelink num="9" /> -->
  <!-- <xacro:sea_joint parent="9" child="10" axis="1 0 0" /> -->
  <!-- <xacro:snakelink num="10" /> -->
  <!-- <xacro:sea_joint parent="10" child="11" axis="0 1 0" /> -->
  <!-- <xacro:snakelink num="11" /> -->
  <!-- <xacro:sea_joint parent="11" child="12" axis="1 0 0" /> -->
  <!-- <xacro:snakelink num="12" /> -->
  <!-- <xacro:sea_joint parent="12" child="13" axis="0 1 0" /> -->
  <!-- <xacro:snakelink num="13" /> -->
  <!-- <xacro:sea_joint parent="13" child="14" axis="1 0 0" /> -->
  <!-- <xacro:snakelink num="14" /> -->
  <!-- <xacro:sea_joint parent="14" child="15" axis="0 1 0" /> -->
  <!-- <xacro:snakelink num="15" /> -->
  <!-- <xacro:sea_joint parent="15" child="16" axis="1 0 0" /> -->
  <!-- <xacro:snakelink num="16" /> -->



  <!-- uncomment for u_snake joints -->

  <xacro:snakelink num="0" />
  <xacro:usnake_joint parent="0" child="1" axis="0 1 0" />
  <xacro:snakelink num="1" />
  <xacro:usnake_joint parent="1" child="2" axis="1 0 0" />
  <xacro:snakelink num="2" />
  <xacro:usnake_joint parent="2" child="3" axis="0 1 0" />
  <xacro:snakelink num="3" />
  <xacro:usnake_joint parent="3" child="4" axis="1 0 0" />
  <xacro:snakelink num="4" />
  <xacro:usnake_joint parent="4" child="5" axis="0 1 0" />
  <xacro:snakelink num="5" />
  <xacro:usnake_joint parent="5" child="6" axis="1 0 0" />
  <xacro:snakelink num="6" />
  <xacro:usnake_joint parent="6" child="7" axis="0 1 0" />
  <xacro:snakelink num="7" />
  <xacro:usnake_joint parent="7" child="8" axis="1 0 0" />
  <xacro:snakelink num="8" />
  <xacro:usnake_joint parent="8" child="9" axis="0 1 0" />
  <xacro:snakelink num="9" />
  <xacro:usnake_joint parent="9" child="10" axis="1 0 0" />
  <xacro:snakelink num="10" />
  <xacro:usnake_joint parent="10" child="11" axis="0 1 0" />
  <xacro:snakelink num="11" />
  <xacro:usnake_joint parent="11" child="12" axis="1 0 0" />
  <xacro:snakelink num="12" />
  <xacro:usnake_joint parent="12" child="13" axis="0 1 0" />
  <xacro:snakelink num="13" />
  <xacro:usnake_joint parent="13" child="14" axis="1 0 0" />
  <xacro:snakelink num="14" />
  <xacro:usnake_joint parent="14" child="15" axis="0 1 0" />
  <xacro:snakelink num="15" />
  <xacro:usnake_joint parent="15" child="16" axis="1 0 0" />
  <xacro:snakelink num="16" />

</robot>
